sonar-project.properties

Co-authored-by: Henrike100 <henrikem100@gmail.com>

fga-eps-mds/2021.1-Oraculo#5 Creating SonarCloud Properties File

---

package.json
src/Pages/LoginScreen/index.js
src/Pages/LoginScreen/styles.js

**Issue:** closes [#57](https://github.com/fga-eps-mds/2021.1-Oraculo/issues/57)
Adicionando dependências "styled components", "react-router-dom" e "antd" ao projeto.

#57 Adicionar a dependência "styled components", "react-router-dom" e "antd"

---

src/Pages/LoginScreen/index.js
src/Routes.js

**Issue:** closes [#30](https://github.com/fga-eps-mds/2021.1-Oraculo/issues/30)
- Adicionando rota para página "criar-processo"

#30 Adicionando rota para página "criar-processo"

---

public/index.html

resolves fga-eps-mds/2021.1-Oraculo#65
Fonte montserrat adicionada como padrão

#65 adicionar fonte montserrat

---

src/Components/BigBlueRectangle/index.js
src/Components/BigBlueRectangle/styles.js
src/Components/BigWhiteRectangle/index.js
src/Components/BigWhiteRectangle/styles.js
src/Components/FieldsGroup/index.js
src/Components/FieldsGroup/styles.js
src/Components/FilterButton/index.js
src/Components/FilterButton/styles.js
src/Components/GenericBlueButton/index.js
src/Components/GenericBlueButton/styles.js
src/Components/GenericRedButton/index.js
src/Components/GenericRedButton/styles.js
src/Components/GenericWhiteButton/index.js
src/Components/GenericWhiteButton/styles.js
src/Components/SearchBar/index.js
src/Components/SearchBar/styles.js
src/style.js

<h1>Resolves fga-eps-mds/2021.1-Oraculo#85</h1>
<h2> Adicionado em styles </h2>
<p>- Tamanho de fonte extra grande
<p>- Cor azul
<h2> Componentes criados </h2>
<p>- Generic White Button
<p>- Generic Red Button
<p>- Generic Blue Button
<p>- Filter Button
<p>- Search Bar
<p>- Big Blue Rectangle
<p>- Big White Rectangle

#85 Criação de componentes para o front end

---

src/Pages/ViewRecord/index.js

Co-authored-by: Joao Paulo Lima da Silva <jpaulo.on@gmail.com>

fga-eps-mds/2021.1-Oraculo#73 fix microservice data acquisition

---

src/Pages/ChangePassword/index.js
src/Pages/DocumentViewScreen/index.js
src/Pages/LoginScreen/index.js
src/Pages/ViewRecord/index.js

**Issue:** closes [#113](https://github.com/fga-eps-mds/2021.1-Oraculo/issues/113)
Padronização de rotas nas páginas.

Padronização de rotas nas páginas

---

src/Pages/CreateUser/index.js
src/Services/Axios/profileService.js

Resolves https://github.com/fga-eps-mds/2021.1-Oraculo/issues/117
- Foram corrigidos os problemas de request para se criar um usuário
- A mudança de todo o arquivo é devido apenas a formatação de espaçamento

117 corrigir cadastro de usuario no frontend

---

src/Components/HeaderWithButtons/index.js
src/Pages/ChangePassword/index.js
src/Pages/CreateProcess/index.js
src/Pages/CreateUser/index.js
src/Pages/DocumentViewScreen/index.js
src/Pages/RegistrationScreen/index.js
src/Pages/ViewProfile/index.js
src/Pages/ViewRecord/index.js

resolves fga-eps-mds/2021.1-Oraculo#114
Descrição do que foi feito:
- Todos os headers de páginas logadas foram substituidos para o novo header com botões funcionais
- Função inutilizada no headerWithButtons removida

114 adicionar o Header da homepage em todas as paginas logadas

---

src/Pages/ViewProfile/index.js
src/Pages/ViewProfile/styles.js
src/Services/Axios/profileService.js

**Issue:** closes [#78](https://github.com/fga-eps-mds/2021.1-Oraculo/issues/78)
Integração do FrontEnd com o microserviço Profile para permitir editar o usuário

78 us28 editar usuario integracao

---

src/Pages/CreateUser/sections.js
src/Pages/ViewProfile/index.js

**Issue** closes fga-eps-mds/2021.1-Oraculo#137
Descrição

137 fix naming errors

---

src/Components/HeaderWithButtons/index.js

**Issue** closes fga-eps-mds/2021.1-Oraculo#125
Descrição

125 modificar header de telas logadas

---

package.json
src/Pages/CreateRecord/index.js
src/Pages/CreateRecord/styles.js
yarn.lock

140 datepicker

---

src/Services/Axios/processService.js
src/Services/Axios/profileService.js

**Issue** closes fga-eps-mds/2021.1-Oraculo#139
Descrição

139 get sections and departments

---

src/Services/Axios/profileService.js

Co-authored-by: Lucas Vieira <lucas.engen@outlook.com>

Erase duplicated function fga-eps-mds/2021.1-Oraculo#149

---

src/Pages/ViewRecord/index.js
src/Pages/ViewRecord/style.js

Resolves fga-eps-mds/2021.1-Oraculo#145
Descrição:
- Todos os dados do registro agora são mostrados na tela de visualizar registros

145 completar dados do registro

---

src/Components/PocketDocument/index.js
src/Components/PocketDocument/styles.js
src/Components/Process/index.js

Resolves fga-eps-mds/2021.1-Oraculo#148
Descrição:
- Agora ao clicar em um registro na página de visualizar registros você é levado a página de visualizar o registro

148 integrar pagina de visualizar todos os registros a de visualizar registro

---

src/Pages/CreateRecord/index.js

Co-authored-by: Co-authored-by: Max Henrique <maxhb.df@gmail.com>

Fix button fga-eps-mds/2021.1-Oraculo#152

---

src/Pages/ViewRecord/index.js

**Issue:** closes [#157](https://github.com/fga-eps-mds/2021.1-Oraculo/issues/157)
Fazer com que o botão de ver processo funcione

Hotfix Botão Voltar em Ver Registro

---

src/Components/HeaderWithButtons/index.js
src/Components/PocketUser/index.js
src/Components/PocketUser/style.js
src/Pages/ViewAllUsers/index.js
src/Pages/ViewAllUsers/styles.js
src/Routes.js
src/Services/Axios/profileService.js

Resolves fga-eps-mds/2021.1-Oraculo#159
Descrição do que foi feito neste pull request:
- Criação da página de listar todos os usuários cadastrados
- Criação de um novo componente para listar todos os usuários cadastrados
- Criação de uma nova rota para a nova página
- Correção da função listAllUsers
- Adição de um botão que leva para a nova página no headerWithButtons

159 listar usuarios

---

src/Pages/AllRegistersScreen/index.js
src/Pages/AllRegistersScreen/styles.js

**Issue:** closes [#155](https://github.com/fga-eps-mds/2021.1-Oraculo/issues/155)
Adicionando barra de pesquina na tela /visualizar-registros

155 barra de pesquisa em todos registros

---

sonar-project.properties

Co-authored-by: Henrike100 <henrikem100@gmail.com>

Update sonar properties file fga-eps-mds/2021.1-Oraculo#168

---

src/Pages/CreateRecord/index.js

Co-authored-by: Lucas Vieira de Jesus <lucas.engen.cc@gmail.com>
Co-authored-by: Victor Rodrigues <victorrsilva17@gmail.com>

fga-eps-mds/2021.1-Oraculo#173 changed value created_by

---

src/Pages/HomePage/index.js
src/Pages/LoginScreen/index.js

Co-authored-by: Henrique Martins <henrikem100@gmail.com

Remove Token Verification fga-eps-mds/2021.1-Oraculo#181

---

src/Pages/AllRegistersScreen/index.js
src/Pages/HomePage/index.js

Resolves fga-eps-mds/2021.1-Oraculo#188
Descrição:
- Alterado o máximo de registros mostrados por página

188 mudar paginacao para mais registros

---

src/Pages/ViewRecord/index.js

Co-authored-by: Gabriel Santos Silva Araújos <gabrielsantos_s96@hotmail.com>

Updating screen when forwarding register fga-eps-mds/2021.1-Oraculo#193

---

README.md
package.json
src/App.test.js
src/Constants/baseUrls.js
src/Pages/CreateRecord/index.js
src/Pages/HomePage/index.js
src/Services/Axios/processService.js

**Issue** closes fga-eps-mds/2021.1-Oraculo#185
Descrição

185 exibir sei existente

---

src/Routes.js

Alerta usuário ao tentar acessar uma rota privada sem estar logado.

204 alertar usuario token expirado

---

src/Components/Departments/index.js
src/Components/PocketDepartment/index.js
src/Pages/EditDepartment/index.js
src/Routes.js
src/Services/Axios/profileService.js

Closes fga-eps-mds/2021.1-Oraculo#187
Descrição:
- Criado uma nova página para a edição de registros
- Agora ao clicar em um Departamento na página de todos os departamentos você é redirecionado para a página de editar esse departamento
- Criado uma nova função para intermediar o post da edição de registro
- Componentes Department e PocketDepartment alterados para conter o id do departamento

187 edicao de departamentos

---

src/Pages/CreateRecord/index.js
src/Pages/EditRecord/index.js

Permite digitar a data, além de escolhe no datepicker

209 datepicker digitado

---

src/Components/Filters/index.js

Co-authored-by: ericoBandeira <ericobandeira@hotmail.com>

Add date filter

---

src/Components/Filters/styles.js
src/Pages/CreateRecord/index.js
src/Pages/ViewAllFields/index.js

Closes fga-eps-mds/2021.1-Oraculo#217
Descrição:
- Remoção dos botões de adicionar campo
- Adicionar filtro na homePage agora tem cursor: pointer

217 retirar botao adicionar campo

---

src/Components/Filters/index.js
src/Pages/CreateRecord/index.js

**Issue:** closes [#219](https://github.com/fga-eps-mds/2021.1-Oraculo/issues/219)
Corrigir palavras sem acentuação ou indevidas

219 corrigir palavras

---

src/Components/Filters/styles.js
src/Pages/EditRecord/index.js
src/Pages/ViewRecord/index.js
src/Pages/ViewRecord/style.js

Closes fga-eps-mds/2021.1-Oraculo#220
Descrição:
- Tamanho máximo da descrição agora é infinito
- Peso das fontes mais leve para mais fácil visualização

220 centralizar nomes do filtro de pesquisa

---

src/Pages/CreateRecord/index.js
src/Pages/EditRecord/index.js

Limita a data de cadastro e edição de registro para a data do dia atual

224 limit register date

---

src/Components/DropDownButton/index.js
src/Pages/AllRegistersScreen/index.js
src/Pages/CreateUser/index.js
src/Pages/CreateUser/sections.js
src/Pages/EditDepartment/index.js
src/Pages/LoginScreen/index.js
src/Pages/ViewProfile/index.js
src/Pages/ViewRecord/index.js
src/Services/Axios/BaseService/baseService.js
src/Services/Axios/processService.js
src/Services/Axios/profileService.js

Remove logs com informações sensiveis e de debug

226 remove logs

---

src/Pages/ChangePassword/index.js
src/Pages/ChangePassword/styles.js

227 input mask

---

src/Components/LoginInput/index.js
src/Components/LoginInput/style.js

Add view input on login screen fga-eps-mds/2021.1-Oraculo#228

---

src/Pages/EditRecord/index.js

Closes fga-eps-mds/2021.1-Oraculo#234
Descrição:
- Colocada uma condição para quando o registro não possuir tags
- Na seleção de estados/UF, required colocado na posição correta

Corrigir erro ao editar registro fga-eps-mds/2021.1-Oraculo#234
